services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: flightbooking
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "flightbooking"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

  # Backend Service (Express + Sequelize)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://myuser:mysecurepassword@postgres:5432/flightbooking
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

