

services:
  backend:
    build:
      context: ./
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://myuser:mysecurepassword@postgres:5432/flightbooking
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: flightbooking-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: flightbooking
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
