services:
  backend:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://ronybubnovsky:dLJgXWD3YpqPDqBG@flightbooking.4cfj2.mongodb.net/?retryWrites=true&w=majority&appName=FlightBooking
