

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Use the DATABASE_URL from environment
    depends_on:
      postgres:
        condition: service_healthy  # Ensure postgres is healthy before starting backend

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Reference environment variable
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Reference environment variable
      POSTGRES_DB: ${POSTGRES_DB}  # Reference environment variable
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
