name: Block PR from noCDbranch to stage/production

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check source and target branches
        if: |
          github.event.pull_request.head.ref == 'noCDbranch' &&
          (github.event.pull_request.base.ref == 'stage' || github.event.pull_request.base.ref == 'production')
        run: |
          echo "PRs from noCDbranch to stage/production are not allowed!"
          exit 1
