name: Flight Booking CI Pipeline

# Trigger the workflow on push or pull request to both main and stage branches
on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install backend dependencies (before Docker setup)
      - name: Install backend dependencies
        working-directory: ./flight-booking-backend
        run: npm install

      # Step 4: Set up MongoDB Atlas environment variable
      - name: Set up MongoDB Atlas connection string
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      # Step 5: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 6: Cleanup previous containers (stop and remove existing containers)
      - name: Cleanup previous containers
        run: |
          docker-compose down || true
          docker ps -a -q | xargs docker stop || true
          docker ps -a -q | xargs docker rm || true

      # Step 7: Set up Docker Buildx (to use Docker compose)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 8: Build and run Docker Compose for backend
      - name: Build and Run Backend with Docker Compose
        working-directory: ./flight-booking-backend
        run: |
          docker-compose up -d --build
        env:
          MONGO_URI: ${{ secrets.MONGODB_URI }} # Use the MongoDB Atlas URI here

      # Step 9: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./flight-booking-frontend
        run: npm install

      # Step 10: Start frontend server in the background
      - name: Start frontend server
        working-directory: ./flight-booking-frontend
        run: npm start &

      # Step 11: Wait for frontend server to be fully ready (20 seconds)
      - name: Wait for frontend server to be ready
        run: sleep 5

      # Step 12: Run Cypress tests in headless mode
      - name: Run Cypress Tests
        working-directory: ./flight-booking-frontend
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: http://localhost:3000

      # Step 13: Upload Cypress Test Results (optional)
      - name: Upload Cypress Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: ./flight-booking-frontend/cypress/videos

      # Step 14: Tear down Docker services
      - name: Tear Down Docker Compose
        working-directory: ./flight-booking-backend
        run: docker-compose down
