name: CI Pipeline

on:
  push:
    branches: [PostgreSQLbranch]
  pull_request:
    branches: [PostgreSQLbranch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: ./flight-booking-backend

      # Step 4: Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./flight-booking-frontend

      # Step 5: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 6: Clean up previous containers (if any)
      - name: Clean up previous containers
        run: |
          docker-compose -f ./flight-booking-backend/docker-compose.yml down || true
          docker system prune -f

      # Step 7: Kill any process using port 5432
      - name: Kill process using port 5432
        run: |
          # Stop any container using port 5432
          CONTAINER_ID=$(sudo lsof -t -i:5432)
          if [ ! -z "$CONTAINER_ID" ]; then
            sudo docker stop $CONTAINER_ID || true
          fi
          # Kill any processes that might still be using the port
          sudo fuser -k 5432/tcp || true
        continue-on-error: true # This ensures the pipeline continues even if no process is found

      # Step 8: Build Docker containers using Docker Compose
      - name: Build and start Docker containers
        run: docker-compose -f docker-compose.yml up --build -d
        working-directory: ./flight-booking-backend

      # Step 9: Start frontend application
      - name: Start frontend application
        run: |
          npm start
        working-directory: ./flight-booking-frontend

      # Step 10: Wait for backend to be ready
      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 3001; then
              echo "Backend is up!";
              break;
            fi
            echo "Waiting for backend to be ready...";
            sleep 5;
          done

      # Step 11: Run Cypress tests
      - name: Run Cypress tests
        working-directory: ./flight-booking-frontend
        run: npx cypress run

      # Step 12: Shut down Docker containers
      - name: Shut down Docker containers
        run: docker-compose -f ./flight-booking-backend/docker-compose.yml down
        working-directory: ./flight-booking-backend
